version: '3.8'

services:
  rag-app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - LOG_PATH=logs/app.log
    volumes:
      - .:/app
      - ./data:/app/data
      - ./logs:/app/logs
    ports:
      - "8501:8501"
    command: streamlit run src/app.py --server.port=8501 --server.address=0.0.0.0
